#!/usr/bin/python3
# -----------------------------------------------------------------------------
# project:  calendarium
# authors:  1966bc aka Giuseppe Costanzi
# licence:  MIT, see LICENSE
# -----------------------------------------------------------------------------
"""The demo icon: a 64 by 64 PNG, in base64.

Generated by tools/make_icon.py, not edited by hand.
"""

PNG = (
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAHWElEQVR42u1b"
    "X2ib1xX/nXu/P5L8r3Eyx2nqYljdOu2emm0JdPB5b6XQwlhFYDM0pOA87aHQ"
    "Qt+MGOyxDJZR2EPAD/VDnLE1bDD25kE9RtlglCSwlQTHSZzWlhPLtix9373n"
    "9MGSY8mWLEuyIwsfuGDZ5zu/7/7uueece+QLNEeoMA5KDhqvsiSTSV32M7UT"
    "Xk1y/vz5eBAEnYcRjxpxwSAIlLX210qpXzKzA+AGM380MzOzWtCTZrr8fuCp"
    "Ot1QAWBjTMr3/Y9FZICITvm+f1kp9SkAKeg0y+33DY/q0CMAcvbs2Xg8Hr9D"
    "RCdEZPP3IgLHcQanp6cfFAjmJqx+vXjSiAdQEASOiFDBUHEwANFaOwA8ALpg"
    "hwBoItK5XC5e0LVlz9YzGsGjIAicagtN1Vgvfrh06VKXn8s5ywDiUUSe68r9"
    "hYXnlrLZ/yilnpPCkhTt+b7/45dPnvx6NZtVnYlEQx4Q7hHPJhLcA8BGEf9h"
    "amq5aGd8fFylUimuhQACIEEQOIMDpy8z1AUjMiSAJwICAQQCW0PzDx/2sLVE"
    "VGqm79Tzy57nsTQpBu4JTwAiCAHGAe4S0edPMpkrN27cWNmJhBJLRYXke+/1"
    "x6y5Tn7sjdAyYmEeWnhzOooIxlrcnX8EYy3KX2iwvx8xzwVLcwjYKx4BYCLk"
    "XB+O44DyuVvrIsmpzz67VU6CU07Gm2/+ynfDxT8hkTifyDwOf7o0r/tzWaUK"
    "05fCJlwD4ffUSRERVFm0eWv+azkJi2jDYRqSevEEQNqLy7+O9Zt0z/FXvXzu"
    "L8n33/8hgCdbt/hmVRUEgTMxMWHP/ej7l51E4nJH5nH47oP/e6dzq0pDyBUm"
    "V5gcYfKEiUXonyqGCLQtkv6E16mXDSl5+ly9oxG841GOhtce6znHD9e7j51Q"
    "2az+3ZUrfw+CwJmdneWSLDAyMrLhFiKjoWU+l57XnTbEmuOBiUqGJYIiKinI"
    "actQIFhS256rd9SLt64dOMx4Y2nesWFehPDu2NiYOz09bcrTIKVSKb70zjtd"
    "VqmXYmFO9YdZFZKGFt4WIS2AbjBelRCZLeuxDIWXJEIfDKImFemN4GkRhEqj"
    "N8xRV36dLOmBaHV1oBjvymMAyPddIXIUM1SVAEYA8iC8zVlEivAVeRAAZyWP"
    "JK+Bm3w+aRRPQaBFIIBmyXlb/1ZCgOe6UusLMQAXwCiv4ltoWAAnYcEgmCYf"
    "0ZqJp5WWigQUpZYVLLqmBeH4RrGGsPDcfpxPG8WTClrOTkAxNjUZLepEm+XK"
    "/ndB6sXz2YB2KMxKMspXPT2ImQhvP7oDzxowUc0v1urtoLce3UFvmMdd/3j1"
    "w9BePOAwSU0eUBTbdtOvHNdUM9tErSzUzI5QO0lJFnhxeRmhdvDn54cg1kKo"
    "nTyAkHE8nMivVE+DAmDJi4OZ22qlBYAWhlfNA3p6erCUTqM7kcCHH36Azs5O"
    "GGNBbeAJn3zyWzx4OI+urq7dPYCUwukXXkBHR3eh/qIa+ou0g6XW0XdcF7LD"
    "+cap2IsLQ8RiIYwxIKJtXZhtxJUZbzV9qXC4q0hAcdLFYa2tfuJSumSrtJp+"
    "TVmgEhHWWty+/b9Nb9hJhoeHEI/HwCwtox+LxSqufM0EFMUYUxWwHKfV9Bsm"
    "YOt2OIz6OKoEjwg4IqCuGCAi0FpjeHioamDxfQ/MGwqtoi81RMKag2AsFqua"
    "V4svV79+fJeF4IbsN0yAiGAvX/XtVV9rrlreWksl9vZqv2EC9rNSEwEWFwGR"
    "yiGpu1ugdZtVgrFYHFpbLC4qnDvn4ckTgGjnImZmJsTwsCAMCcymvSrBoges"
    "rFAV/DavBF13Y/UreUC5mWZVgg5aRESeTlzk4HBbrhA6yMm3JAEH3X57ppWg"
    "CMNaQne34IsvQlTrww4OCowBiKS9KkERwHGAM2dklyxUuj3aqhIUAcKQdtka"
    "0tD7tHQluLFi5qgneNQTPOoJHvUEn21LLNwtFB9iqeQoJQQkEglDRMzMbfXt"
    "sIjAWt5INmUTc57qCBFRZnR0dDaTyRybm5uT3t7v6Xw+D601XnllqGrHxvOe"
    "VoJKqZbQN8bA9+OYm5uVb75ZgOd5j9bW1u4DQCqVkpIgODIyogEYpdR113Vf"
    "v3btj+Frr/1Ax+OdMCaHRCK+K8vFlENELaHvOD4AhWvXrltm63qe99fJycn1"
    "IAic4v8LbzaZZmdnZXx8XKXT6f8S0c/T6XTf7du3wlOn+qmrq7vkJSqNrRGZ"
    "mZ+pvrWMe/fmcPXqVfPll/92XdddCsPwFzdv3ly5ePEipqenNy8ebUrxMsGF"
    "CxfO+L7/uTFmiJnR19cH13XRvFtw+x7yYK3FwsICrLXwff/bKIqSk5OT/yi/"
    "MLEtNm7eGkkmezs6Oj621v4sn8+/yMxupWdaLeYVton1ff+B1vpv2Wz2N1NT"
    "U/eSyaSempqypVTtIFtZGhsbc6MoGiAi93ClPbLGmPsTExO58jnVbKNw5exQ"
    "SzKZ1MW7ATtvlhqIGB8fP5QFUiHVCY6ksnwHCpiyCX+RRUIAAAAASUVORK5C"
    "YII="
)
