#!/usr/bin/python3
# -----------------------------------------------------------------------------
# project:  calendarium
# authors:  1966bc aka Giuseppe Costanzi
# licence:  MIT, see LICENSE
# -----------------------------------------------------------------------------
"""Draw the demo icon, once, and write it into examples/icon.py as base64.

A build tool, not part of the demo. It needs Pillow, the demo does not:
the PNG is drawn when the picture changes and the result is committed.

The picture is a calendar page: a red header with two binding rings, a
grid of days, and one day picked out in the blue of the spinboxes. It is
drawn at eight times the final size and reduced, so the edges stay smooth.

    python3 tools/make_icon.py
"""

import base64
import io
import os

from PIL import Image, ImageDraw

SIZE = 64
SCALE = 8

PAPER = (250, 250, 247, 255)
EDGE = (90, 90, 90, 255)
HEADER = (192, 57, 43, 255)
RING = (60, 60, 60, 255)
DAY = (200, 200, 200, 255)
PICKED = (0, 0, 255, 255)

MODULE_WIDTH = 60

MODULE = '''#!/usr/bin/python3
# -----------------------------------------------------------------------------
# project:  calendarium
# authors:  1966bc aka Giuseppe Costanzi
# licence:  MIT, see LICENSE
# -----------------------------------------------------------------------------
"""The demo icon: a {size} by {size} PNG, in base64.

Generated by tools/make_icon.py, not edited by hand.
"""

PNG = (
{body}
)
'''


def draw(size=SIZE):
    """The icon at size pixels; the social preview asks for a larger one."""
    side = size * SCALE
    image = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    pen = ImageDraw.Draw(image)
    u = side / 64.0  # one pixel of the icon as drawn at 64

    # The page, and its header drawn over the top of it.
    page = (4 * u, 8 * u, 60 * u, 60 * u)
    pen.rounded_rectangle(page, radius=6 * u, fill=PAPER,
                          outline=EDGE, width=int(2 * u))
    pen.rounded_rectangle((4 * u, 8 * u, 60 * u, 24 * u), radius=6 * u,
                          fill=HEADER, outline=EDGE, width=int(2 * u))
    pen.rectangle((5 * u, 18 * u, 59 * u, 24 * u), fill=HEADER)
    pen.line((4 * u, 24 * u, 60 * u, 24 * u), fill=EDGE, width=int(2 * u))

    # Two binding rings, standing over the header.
    for x in (18, 46):
        pen.rounded_rectangle(((x - 3) * u, 3 * u, (x + 3) * u, 15 * u),
                              radius=3 * u, fill=RING)

    # Three rows of four days, one of them picked.
    for row in range(3):
        for col in range(4):
            x = 10 * u + col * 12 * u
            y = 29 * u + row * 10 * u
            colour = PICKED if (row, col) == (1, 2) else DAY
            pen.rectangle((x, y, x + 8 * u, y + 6 * u), fill=colour)

    return image.resize((size, size), Image.LANCZOS)


def write_module(image, path):
    buffer = io.BytesIO()
    image.save(buffer, format="PNG", optimize=True)
    text = base64.b64encode(buffer.getvalue()).decode("ascii")
    lines = [text[i:i + MODULE_WIDTH] for i in range(0, len(text), MODULE_WIDTH)]
    body = "\n".join('    "{0}"'.format(line) for line in lines)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(MODULE.format(size=SIZE, body=body))
    return len(buffer.getvalue())


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    count = write_module(draw(), os.path.join(root, "examples", "icon.py"))
    print("icon.py written, {0} bytes of PNG".format(count))


if __name__ == "__main__":
    main()
